///|
#deprecated
#doc(hidden)
pub extend AeadAlgorithm with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AeadAlgorithm with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend AeadSealed with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AeadSealed with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CipherAlgorithm with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CipherAlgorithm with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CryptoError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CryptoError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DigestAlgorithm with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DigestAlgorithm with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend KeyAlgorithm with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend KeyAlgorithm with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SignatureAlgorithm with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SignatureAlgorithm with Eq::{not_equal, equal}
