///|
#deprecated
#doc(hidden)
pub extend ChannelType with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ChannelType with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DataChannel with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DataChannel with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DataChannelCommand with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DataChannelCommand with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DataChannelConfig with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DataChannelConfig with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DataChannelError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DataChannelError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DataChannelEvent with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DataChannelEvent with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DataChannelMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DataChannelMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DataChannelState with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DataChannelState with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DcepMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DcepMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DcepOpen with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DcepOpen with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend PayloadProtocolIdentifier with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend PayloadProtocolIdentifier with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend StreamRole with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend StreamRole with Eq::{not_equal, equal}
