///|
#deprecated
#doc(hidden)
pub extend AlertDescription with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AlertDescription with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend AlertLevel with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AlertLevel with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CertificateKeyType with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CertificateKeyType with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CertificateMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CertificateMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CertificateRequestMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CertificateRequestMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CertificateVerifyMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CertificateVerifyMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CipherSuite with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CipherSuite with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ClientHelloMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ClientHelloMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ClientKeyExchangeMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ClientKeyExchangeMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ContentType with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ContentType with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DtlsError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DtlsError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DtlsEvent with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DtlsEvent with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Fingerprint with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Fingerprint with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend FingerprintAlgorithm with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend FingerprintAlgorithm with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend FinishedMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend FinishedMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend HandshakeFragment with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend HandshakeFragment with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend HandshakeMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend HandshakeMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend HandshakePhase with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend HandshakePhase with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend HandshakeType with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend HandshakeType with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend HelloExtensions with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend HelloExtensions with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend HelloVerifyRequestMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend HelloVerifyRequestMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ProtocolVersion with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ProtocolVersion with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Record with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Record with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RecordHeader with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RecordHeader with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Role with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Role with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ServerHelloMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ServerHelloMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ServerKeyExchangeMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ServerKeyExchangeMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SrtpProtectionProfile with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SrtpProtectionProfile with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend State with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend State with Eq::{not_equal, equal}
