///|
#deprecated
#doc(hidden)
pub extend CandidatePairStats with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CandidatePairStats with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CodecStats with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CodecStats with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DataChannelStats with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DataChannelStats with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DetailedStatsReport with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DetailedStatsReport with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IceServer with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IceServer with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend OfferCollisionPolicy with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend OfferCollisionPolicy with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend PeerConnectionState with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend PeerConnectionState with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend PeerEvent with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtcError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtcError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RtcMessage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtcMessage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RtcStreamOwner with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtcStreamOwner with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RtpStreamStats with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtpStreamStats with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend StatsReport with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend StatsReport with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransportStats with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TransportStats with Eq::{not_equal, equal}
