///|
#deprecated
#doc(hidden)
pub extend ApplicationDefinedPacket with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ApplicationDefinedPacket with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ExtendedReportBlock with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ExtendedReportBlock with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ExtendedReportPacket with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ExtendedReportPacket with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend FullIntraRequestEntry with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend FullIntraRequestEntry with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend FullIntraRequestPacket with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend FullIntraRequestPacket with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend GoodbyePacket with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend GoodbyePacket with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Header with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Header with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend NackPair with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend NackPair with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Packet with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Packet with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend PictureLossIndicationPacket with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend PictureLossIndicationPacket with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ReceiverEstimatedMaximumBitratePacket with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ReceiverEstimatedMaximumBitratePacket with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ReceiverReportPacket with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ReceiverReportPacket with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ReceptionReport with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ReceptionReport with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RtcpError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtcpError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SenderReportPacket with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SenderReportPacket with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SourceDescriptionChunk with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SourceDescriptionChunk with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SourceDescriptionItem with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SourceDescriptionItem with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SourceDescriptionPacket with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SourceDescriptionPacket with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SourceDescriptionType with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SourceDescriptionType with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransportLayerNackPacket with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TransportLayerNackPacket with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransportWideCcPacket with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TransportWideCcPacket with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransportWideStatus with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TransportWideStatus with Eq::{not_equal, equal}
