///|
#deprecated
#doc(hidden)
pub extend CandidateAddress with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CandidateAddress with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CandidatePair with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CandidatePair with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CandidatePairState with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CandidatePairState with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CandidateType with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CandidateType with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IceCandidate with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IceCandidate with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IceConnectionState with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IceConnectionState with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IceCredentials with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IceCredentials with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IceError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IceError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IceEvent with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IceEvent with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IceGatheringState with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IceGatheringState with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IceRole with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IceRole with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IceTransportPolicy with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IceTransportPolicy with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SrflxEvent with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SrflxEvent with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SrflxGatheringState with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SrflxGatheringState with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TcpCandidateType with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TcpCandidateType with Eq::{not_equal, equal}
