///|
#deprecated
#doc(hidden)
pub extend Attribute with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Attribute with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend AttributeType with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AttributeType with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Message with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Message with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend MessageClass with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend MessageClass with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Method with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Method with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ResponseError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ResponseError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend StunError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend StunError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransactionEvent with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TransactionEvent with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransactionEventKind with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TransactionEventKind with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransactionId with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TransactionId with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransactionId with Hash::{hash, hash_combine}
