///|
#deprecated
#doc(hidden)
pub extend AbsSendTimeExtension with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AbsSendTimeExtension with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend AudioLevelExtension with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AudioLevelExtension with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CameraDirection with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CameraDirection with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend HeaderExtension with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend HeaderExtension with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Packet with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Packet with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend PayloadCodec with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend PayloadCodec with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend PlayoutDelayExtension with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend PlayoutDelayExtension with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RtpError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtpError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransportCcExtension with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TransportCcExtension with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend VideoOrientationExtension with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend VideoOrientationExtension with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend VideoRotation with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend VideoRotation with Eq::{not_equal, equal}
