///|
#deprecated
#doc(hidden)
pub extend Context with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Context with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Direction with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Direction with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend InterceptorError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend InterceptorError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Packet with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Packet with Eq::{not_equal, equal}
