///|
#deprecated
#doc(hidden)
pub extend DataChannelParameters with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DataChannelParameters with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DtlsFingerprint with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DtlsFingerprint with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DtlsSetup with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DtlsSetup with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend MediaDescription with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend MediaDescription with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend MediaDirection with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend MediaDirection with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RidDirection with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RidDirection with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RtpCodecParameters with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtpCodecParameters with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RtpHeaderExtensionParameters with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtpHeaderExtensionParameters with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RtpMediaParameters with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtpMediaParameters with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RtpStreamParameters with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtpStreamParameters with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SdpAttribute with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SdpAttribute with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SdpDocument with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SdpDocument with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SdpError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SdpError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SdpField with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SdpField with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SdpType with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SdpType with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SessionDescription with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SessionDescription with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SignalingState with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SignalingState with Eq::{not_equal, equal}
