///|
#deprecated
#doc(hidden)
pub extend AudioBuffer with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AudioBuffer with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend AudioLayout with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AudioLayout with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CodecCapability with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend CodecCapability with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend EncodedFrameContext with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend EncodedFrameContext with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend H26xCodec with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend H26xCodec with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend H26xNal with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend H26xNal with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IvfCodec with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IvfCodec with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IvfFrame with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IvfFrame with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IvfHeader with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IvfHeader with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend MediaError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend MediaError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend MediaKind with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend MediaKind with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend MediaTrack with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend OggHeader with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend OggHeader with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend OggPacket with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend OggPacket with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend OggPage with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend OggPage with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend OggPageHeader with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend OggPageHeader with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend OpusTags with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend OpusTags with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RtpEncodingParameters with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtpEncodingParameters with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RtpParameters with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtpParameters with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RtpReceiver with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtpSender with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RtpTransceiver with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Sample with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Sample with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransceiverDirection with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TransceiverDirection with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransformDirection with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TransformDirection with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend UserComment with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend UserComment with Eq::{not_equal, equal}
