///|
#deprecated
#doc(hidden)
pub extend AddressError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AddressError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ClockSample with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ClockSample with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ConnectionId with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ConnectionId with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ConnectionId with Hash::{hash, hash_combine}

///|
#deprecated
#doc(hidden)
pub extend Duration with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Duration with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
#deprecated
#doc(hidden)
pub extend Duration with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend EcnCodepoint with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend EcnCodepoint with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend InboundDatagram with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend InboundDatagram with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Instant with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Instant with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
#deprecated
#doc(hidden)
pub extend Instant with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IoAction with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IoAction with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IoEvent with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IoEvent with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend IpAddress with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend IpAddress with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ListenerId with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ListenerId with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ListenerId with Hash::{hash, hash_combine}

///|
#deprecated
#doc(hidden)
pub extend OutboundDatagram with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend OutboundDatagram with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SocketAddress with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SocketAddress with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TimeError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TimeError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransportContext with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TransportContext with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TransportProtocol with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TransportProtocol with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend WallTime with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend WallTime with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
#deprecated
#doc(hidden)
pub extend WallTime with Eq::{not_equal, equal}
