///|
#deprecated
#doc(hidden)
pub extend AllocationEvent with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AllocationEvent with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend AllocationId with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AllocationId with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend AllocationId with Hash::{hash, hash_combine}

///|
#deprecated
#doc(hidden)
pub extend AllocationState with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AllocationState with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RelayedAddress with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend RelayedAddress with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TurnCredentials with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TurnCredentials with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TurnError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TurnError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend TurnTransport with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend TurnTransport with Eq::{not_equal, equal}
