///|
#deprecated
#doc(hidden)
pub extend MdnsError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend MdnsError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend MdnsEvent with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend MdnsEvent with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Mode with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Mode with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend OutboundQuery with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend OutboundQuery with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Query with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Query with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend QueryId with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend QueryId with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend QueryId with Hash::{hash, hash_combine}

///|
#deprecated
#doc(hidden)
pub extend Resolution with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Resolution with Eq::{not_equal, equal}
