///|
#deprecated
#doc(hidden)
pub extend AssociationEvent with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AssociationEvent with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend AssociationRole with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AssociationRole with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend AssociationState with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend AssociationState with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Chunk with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Chunk with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend DataChunk with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend DataChunk with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ForwardTsn with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ForwardTsn with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ForwardTsnStream with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ForwardTsnStream with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend GapAckBlock with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend GapAckBlock with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend InitChunk with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend InitChunk with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Message with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Message with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Ordering with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Ordering with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Packet with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Packet with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Parameter with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Parameter with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend ReconfigParameter with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend ReconfigParameter with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Reliability with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend Reliability with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SackChunk with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SackChunk with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend SctpError with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend SctpError with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend StreamId with Debug::{to_repr}

///|
#deprecated
#doc(hidden)
pub extend StreamId with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend StreamId with Hash::{hash, hash_combine}
